=== QuTech-Delft/qne-adk/src/adk/schema/networks/node_asset.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "file:node_asset.json",
  "title": "Node",
  "description": "Node in a Network object as part of an Asset",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "maxLength": 64
    },
    "slug": {
      "type": "string",
      "pattern": "^[-a-zA-Z0-9_]+$"
    },
    "coordinates": {
      "type": "object",
      "properties": {
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        }
      }
    },
    "node_parameters": {
      "type": "array",
      "items": {
        "$ref": "file:/networks/template.json"
      }
    },
    "qubits": {
      "type": "array",
      "items": {
        "$ref": "file:/networks/qubit.json"
      }
    }
  },
  "additionalProperties": false
}

=== QuTech-Delft/qne-adk/docs/json_examples/experiment_node_example.json
{
  "name": "Amsterdam",
  "slug": "amsterdam",
  "coordinates": {
    "latitude": 52.3667,
    "longitude": 4.8945
  },
  "node_parameters": [
    {
      "slug": "gate-fidelity",
      "values": [
        {
          "name": "gate_fidelity",
          "value": 1.0,
          "scale_value": 1.0
        }
      ]
    }
  ],
  "qubits": [
    {
      "qubit_id": 0,
      "qubit_parameters": [
        {
          "slug": "relaxation-time",
          "values": [
            {
              "name": "t1",
              "value": 0,
              "scale_value": 1.0
            }
          ]
        },
        {
          "slug": "dephasing-time",
          "values": [
            {
              "name": "t2",
              "value": 0,
              "scale_value": 1.0
            }
          ]
        }
      ]
    },
    {
      "qubit_id": 1,
      "qubit_parameters": [
        {
          "slug": "relaxation-time",
          "values": [
            {
              "name": "t1",
              "value": 0,
              "scale_value": 1.0
            }
          ]
        },
        {
          "slug": "dephasing-time",
          "values": [
            {
              "name": "t2",
              "value": 0,
              "scale_value": 1.0
            }
          ]
        }
      ]
    },
    {
      "qubit_id": 2,
      "qubit_parameters": [
        {
          "slug": "relaxation-time",
          "values": [
            {
              "name": "t1",
              "value": 0,
              "scale_value": 1.0
            }
          ]
        },
        {
          "slug": "dephasing-time",
          "values": [
            {
              "name": "t2",
              "value": 0,
              "scale_value": 1.0
            }
          ]
        }
      ]
    }
  ]
}
